version: "3.7"

networks:
    redio_network:

x-common-variables: &common-variables
    APP_DEBUG: "true"
    APP_ENV: local
    DB_CONNECTION: mysql
    DB_HOST: mysql_db
    DB_PORT: 3306
    DB_USERNAME: root
    DB_PASSWORD: mysql
    MAIL_DRIVER: smtp
    MAIL_HOST: mailhog
    MAIL_PORT: 1025
    MAIL_USERNAME: "null"
    MAIL_PASSWORD: "null"
    MAIL_ENCRYPTION: "null"


services:
    mysql_db:
        image: mysql:8.0
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: api
        ports:
            - 3326:3306
        volumes:
            - ./_data/mysql:/var/lib/mysql
        networks:
            - redio_network

    mailhog:
        image: mailhog/mailhog
        command: ["-smtp-bind-addr", "0.0.0.0:1025"]
        ports:
            - 1225:1025 # smtp server
            - 8225:8025 # web ui
        networks:
            - redio_network

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - ./api:/app
            - ./api/storage/logs/php-fpm:/var/log/php-fpm
        networks:
            - redio_network
        ports:
            - "7000:80"
        environment:
            <<: *common-variables
            APP_SLUG: redio
            APP_NAME: Redio
            WEB_DOCUMENT_ROOT: /app/redio/public
            DB_DATABASE: api
            QUEUE_CONNECTION: sync
            PHP_OPCACHE_MEMORY_CONSUMPTION: 256
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 32531
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: "true"
        depends_on:
            - mysql_db

    mercure:
        image: dunglas/mercure
        environment:
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
            SERVER_NAME: ":80"
        ports:
            - "9090:80"
        networks:
            - redio_network
        volumes:
            - ./_data/caddy_data:/data
            - ./_data/caddy_config:/config
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev